baseURL = "http://example.com/"
languageCode = "en-us"
title = "Public Data"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Calin Tataru"
    description = "This site will document publicly available sources of data of interest to P&C actuaries"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/cas/"
    name = "CAS"
    weight = 2

[[menu.main]]
    url = "/r-packages/"
    name = "R packages"
    weight = 3
  
[[menu.main]]
    url = "/web/"
    name = "Web source"
    weight = 4
    
[[menu.main]]
    url = "/api/"
    name = "API"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight = 2
